---
#
# Ansible managed
#
repository:
  description: Supervisor (process state manager) for Linux.
  homepage: https://buluma.github.io/
  topics: system, server, process, supervisor, supervisord, manager, init, docker, ansible, molecule, tox, playbook, hacktoberfest
