---
- name: Load a variable file based on the OS type.
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Ensure supervisor is installed.
  ansible.builtin.pip:
    name: supervisor
    state: present
    version: "{{ supervisor_version | default(omit) }}"

- name: Ensure supervisor log dir exists.
  ansible.builtin.file:
    path: "{{ supervisor_log_dir }}"
    state: directory
    mode: 0755

- include_tasks: config.yml

- include_tasks: init-setup.yml
  when: supervisor_started or supervisor_enabled

- name: Ensure supervisor is started (if configured).
  ansible.builtin.service:
    name: supervisord
    state: started
  when: supervisor_started

- name: Ensure supervisor is enabled at boot (if configured).
  ansible.builtin.service:
    name: supervisord
    enabled: true
  when: supervisor_enabled
