---
- name: Converge
  hosts: all
  become: true

  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

  vars:
    supervisor_user: root
    supervisor_password: fizzbuzz

  pre_tasks:
    - name: update apt cache (Debian).
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    # Install curl for test purposes.
    - name: install curl for testing purposes.
      package: name=curl state=present

    # Install Apache for test purposes.
    - block:
        - name: install Apache (RedHat).
          package: name=httpd state=present
        - name: ensure Apache is not running (RedHat).
          service: name=httpd state=stopped enabled=no
      when: ansible_os_family == 'RedHat'

    - block:
        - name: install Apache (Debian).
          package: name=apache2 state=present
        - name: ensure Apache is not running (Debian).
          service: name=apache2 state=stopped enabled=no
      when: ansible_os_family == 'Debian'

    - name: create a test HTML file to load.
      ansible.builtin.copy:
        content: "<html><head><title>Test</title></head><body>Test.</body></html>"
        dest: /var/www/html/index.html
        force: false
        group: root
        owner: root
        mode: 0644

    # Add Apache to supervisor_programs.
    - name: set Apache start command (Debian).
      ansible.builtin.set_fact:
        apache_start_command: apache2ctl -DFOREGROUND
      when: ansible_os_family == 'Debian'

    - name: set Apache start command (RedHat).
      ansible.builtin.set_fact:
        apache_start_command: httpd -DFOREGROUND
      when: ansible_os_family == 'RedHat'

    - name: add Apache to supervisor_programs.
      ansible.builtin.set_fact:
        supervisor_programs:
          - name: 'apache'
            command: "{{ apache_start_command }}"
            state: present
            configuration: |
              autostart=true
              autorestart=true
              startretries=1
              startsecs=1
              redirect_stderr=true
              stderr_logfile=/var/log/apache-err.log
              stdout_logfile=/var/log/apache-out.log
              user=root
              killasgroup=true
              stopasgroup=true

  roles:
    - role: buluma.supervisor

  tasks:
    - name: trigger handlers so supervisor runs everything it should run.
      meta: flush_handlers

  post_tasks:
    - name: wait for Apache to come up (if it's going to do so...).
      ansible.builtin.wait_for:
        port: 80
        delay: 2

    - name: verify Apache is responding on port 80.
      ansible.builtin.uri:
        url: http://127.0.0.1/
        method: GET
        status_code: 200

    - name: verify supervisorctl is available.
      command: supervisorctl --help
      args:
        warn: false
      changed_when: false

    - name: validate supervisorctl works through the default UNIX socket.
      community.general.supervisorctl:
        name: apache
        state: restarted
        username: "{{ supervisor_user }}"
        password: "{{ supervisor_password }}"
      changed_when: false

    - name: validate supervisorctl works with unix socket
      command: supervisorctl status
      args:
        warn: false
      changed_when: false
