---
- name: Converge
  hosts: all
  become: true

  vars:
    supervisor_unix_http_server_enable: false
    supervisor_inet_http_server_enable: true
    supervisor_inet_http_server_port: '*:9001'

  pre_tasks:
    - name: update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: buluma.supervisor

  tasks:
    - name: validate Supervisor is responding to requests through the web UI.
      uri:
        url: http://localhost:9001/
        method: GET
        user: "{{ supervisor_user }}"
        password: "{{ supervisor_password }}"
        status_code: 200

    - name: validate Supervisor rejects unauthenticated requests to the web UI.
      uri:
        url: http://localhost:9001/
        method: GET
        user: "{{ supervisor_user }}"
        password: "fizzbuzz"
        status_code: 401

    - name: validate supervisorctl works with inet
      command: supervisorctl status
      args:
        warn: false
      changed_when: false
