---
- name: Verify
  hosts: all
  become: no
  gather_facts: no

  tasks:
    - name: test connection
      ansible.builtin.ping:

    - name: wait for Apache to come up (if it's going to do so...).
      ansible.builtin.wait_for:
        port: 80
        delay: 2

    - name: verify Apache is responding on port 80.
      ansible.builtin.uri:
        url: http://127.0.0.1/
        method: GET
        status_code: 200

    - name: verify supervisorctl is available.
      command: supervisorctl --help
      args:
        warn: false
      changed_when: false

    - name: validate supervisorctl works through the default UNIX socket.
      community.general.supervisorctl:
        name: apache
        state: restarted
        username: "{{ supervisor_user }}"
        password: "{{ supervisor_password }}"
      changed_when: false

    - name: validate supervisorctl works with unix socket
      command: supervisorctl status
      args:
        warn: false
      changed_when: false
